### ISSUE TITLE
Starting contract helper with defaults results in error loop. 

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/near-contract-helper#32]
Error message is unhelpful: 
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/Users/evgueniadegtiareva/near/near-contract-helper/app.js:28:29)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Program node app exited with code 1

**Comment by janedegtiareva** [comment]
I believe this happens when there is no key file
